from src.exceptions.exceptions import CPFException


def calc_cpf(cpf: str) -> None:
    pass
